project:
  type: website
  output-dir: docs

website:
  title: "Arcadia Workflows Documentation"
  favicon: "logos/Arcadia_white_symbol_logo.png"

  navbar:
    background: light
    logo: "logos/Arcadia_symbol_logo_cropped.png"
    title: Arcadia Workflows Documentation

    right:
      - icon: twitter
        href: https://twitter.com/ArcadiaScience
      - icon: github
        href: https://github.com/Arcadia-Science

  sidebar:
    links:
      - icon: Github
        href: https://github.com/Arcadia-Science
    margin-header: test
    style: "docked"
    contents:
    - section: "Workflows"
      contents:
        - href: pages/overview.qmd
          text: "Overview"
        - href: pages/metagenomics-workflows/metagenomics.qmd
          text: "metagenomics"
    - section: "Resources"
      contents:
        - href: pages/resources/nextflow-quick-start.qmd
          text: Nextflow Resources
        - href: pages/resources/nf-core-template-guidelines.qmd
          text: nf-core Template Guidelines
        - href: pages/resources/container-guidelines.qmd
          text: Container Guidelines

format:
  html:
    theme: default
    css: styles.css
    toc: true

editor: visual
